### PR TITLE
Avoid to stop building if platform is already added

### PR DESCRIPTION
**Pull request by dannywillems**

### CODE REVIEW

**Comment by dannywillems** [comment]
Something wrong with this PR?

**Comment by pwbs** [comment]
@dannywillems I think the patch isn't quite right. For instance, if you don't have the rights to write in $(CORDOVAPATH), with your patch, it won't fail. If you want it not to fail when the platform already exists, I think you have to do something a little more complex...

**Comment by pwbs** [comment]
perhaps merge it and make it better later...

**Comment by dannywillems** [comment]
@pwbs I think a FIXME/NOTE message in comment before could be a compromise. What do you think?

**Comment by dannywillems** [comment]
I can't reproduce the error so I close the error and I will reopen it when I will be able to reproduce it.

**Pull request merged**
