### PR TITLE
rename ocsigen-start

### PR DESCRIPTION
**Pull request by canonici**
renamed every occurrence of eba to os

### CODE REVIEW

**Comment by vasilisp** [comment]
This will break the template as far as I can see, but that's OK, we will get back a working template with a rebased #81 .

**Comment by pwbs** [comment]
Don't forget to make http://www.ocsigen.org/ocsigen-start work... ;)

**Comment by vasilisp** [comment]
@balat @vouillon can you start your migration to the `Os_` modules so that we can proceed with the renaming? Thanks!

**Comment by pwbs** [comment]
I think you should rename before we switch... Otherwise, to switch, we'd have to pin the branch of the PR (or a clone of it).

**Comment by vasilisp** [comment]
OK, then we need one of @balat @vouillon @Drup to rename the repo. I don't have permissions to do that. We can merge the PR immediately thereafter, and then you switch.

**Comment by pwbs** [comment]
I think it should be more like 
- make a new repo, name it ocsigen-start, push the stuff there
- display a big redirection link on this repo, then switch it to read-only

**Comment by Drup** [comment]
Github automatically keep a redirection for renamed projects. No need to do a complicated scheme, especially for a project that was never properly released.

**Comment by Drup** [comment]
Done.

**Comment by pwbs** [comment]
Oh, nice, I didn't know! :)

(However I suppose it doesn't happen when it's moved from an account to another?)

**Comment by Drup** [comment]
If you move from one account to another, the old one is mark as a forked, iirc.

**Comment by pwbs** [comment]
Please merge! ;-)

**Pull request merged**
