### PR TITLE
[ci] Automate the build process using GitHub Actions instead of Travis CI

### PR DESCRIPTION
**Pull request by ilankri**

### CODE REVIEW

**Comment by smorimoto** [comment]
I recommend using v2 instead.

**Comment by ilankri** [comment]
> I recommend using v2 instead.

But this version is not yet released, no? I am a little uncomfortable with using an unreleased version.

**Comment by smorimoto** [comment]
> But this version is not yet released, no? I am a little reluctant to use an unreleased version.

Well, that's true, but v2 actually includes a lot of fixes and improvements.

**Comment by smorimoto** [comment]
Since it was officially released, I changed it to use ocaml/setup-ocaml instead :)

**Review by smorimoto — APPROVED** [review]

**Pull request merged**
