### PR TITLE
Userid as first parameter for consistency.

### PR DESCRIPTION
**Pull request by dannywillems**
If it's ok, BS must be changed first @balat.

### CODE REVIEW

**Comment by vasilisp** [comment]
Looks OK to me.

**Comment by pwbs** [comment]
Since we're changing that... why not label the parameters?

**Comment by dannywillems** [comment]
@pwbs You will also need to change BS because some functions aren't labeled and the order changed.

**Comment by pwbs** [comment]
> @pwbs You will also need to change BS because some functions aren't labeled and the order changed.

Yes, of course. My point is, since we're breaking the compatibility, we may make even more changes. :)

**Pull request merged**
