### PR TITLE
create ocsipersist database on "make db-create"

### PR DESCRIPTION
**Pull request by jrochel**

### CODE REVIEW

**Comment by dannywillems** [comment]
@jrochel It's not created in the SQL file?

**Comment by jrochel** [comment]
That's right, but I thought that it's better to include it here too as it's a CREATE DATABASE, not just a CREATE TABLE, and thus on a different level. To be honest I'm not sure whether this is actually very helpful but I thought it couldn't hurt.

**Comment by dannywillems** [comment]
@jrochel Maybe add `IF NOT EXISTS` to avoid error when we have multiple ocsigen-start projects?
It's also `CREATE DATABASE ocsipersist` in `PROJECT_NAME.sql`.

**Comment by jrochel** [comment]
"CREATE DATABASE IF NOT EXISTS" NOT EXISTS.
I could add a "|| true" in the Makefile but I don't really see the point. But I have removed the line from PROJECT_NAME.sql.

**Pull request closed without merging**
