### PR TITLE
Userid --> myid convention

### PR DESCRIPTION
**Pull request by dannywillems**

### CODE REVIEW

**Comment by vasilisp** [comment]
To be honest, I find `user` clearer. Does `my` resolve some ambiguity somewhere?

**Comment by dannywillems** [comment]
@balat said the convention was `myid` for functions called in a session. For me, it doesn't make a big difference. I even prefer `userid` than `myid`.

**Comment by vasilisp** [comment]
OK, makes sense if we are consistent about it. Please rebase :).

**Comment by dannywillems** [comment]
@vasilisp I wait the merge #167 because there will be new conflicts...

**Comment by dannywillems** [comment]
@vasilisp Ok. Fixed.

**Pull request merged**
