### PR TITLE
Add some reserve filenames for template: local, os_otdemo, db

### PR DESCRIPTION
**Pull request by dannywillems**
@vasilisp I forgot local and os_otdemo last time.

db is new since #123.

### CODE REVIEW

**Comment by vasilisp** [comment]
What does `os_otdemo` conflict with?

**Comment by dannywillems** [comment]
@vasilisp : PROJECT_NAME.css

**Comment by dannywillems** [comment]
font-awesome.min is not mandatory because we can't have a dot in the project name.

**Comment by vasilisp** [comment]
Thanks, you are right. Merging.

**Pull request merged**
