### PR TITLE
Eba_lib: base_and_path_of_url: useful when you want to split

### PR DESCRIPTION
**Pull request by dannywillems**

### CODE REVIEW

**Comment by dannywillems** [comment]
@vasilisp do you think is useless or you forgot this PR? :)

**Comment by pwbs** [comment]
@dannywillems meanwhile, your branch has conflicts... ;)

**Comment by dannywillems** [comment]
@pwbs I think it will be better to close it and I will add it when I will PR OAuth2 and OpenID Connect.

**Comment by vasilisp** [comment]
@dannywillems, the code looks good, but I am not exactly sure what `Eba_lib` should contain. Also, I would be a bit reluctant to add new URL manipulation functions in a new place; we already have multiple `Url` modules in Ocsigenserver and Eliom and inconsistencies between client and server.

**Pull request closed without merging**
