### PR TITLE
Eba notif

### PR DESCRIPTION
**Pull request by canonici**
Updated to use eliom_notif.

### CODE REVIEW

**Comment by vasilisp** [comment]
@balat, do you want to test this before we merge it? It looks OK to me.

@canonici, I feel tempted to squash the commits because the history is not all that clean (all the fix and corr are for what?). Do you want to force-push a cleaned-up history? Or I can do it and merge manually, as you wish.

**Comment by pwbs** [comment]
> @canonici, I feel tempted to squash the commits because the history is not all that clean (all the fix and corr are for what?). Do you want to force-push a cleaned-up history? Or I can do it and merge manually, as you wish.

I concur!

**Comment by canonici** [comment]
I squashed the commits.

**Comment by vasilisp** [comment]
We need to rebase this on top of master, and re-implement `unlisten_user` (#104) in Eliom. Not entirely trivial because of the change away from volatile references (whose consequences I don't exactly understand).

**Comment by vasilisp** [comment]
Superseded by #314.

**Pull request closed without merging**
