### PR TITLE
Fix continuous integration

### PR DESCRIPTION
**Pull request by dannywillems**
See #165.

@Drup It must fix the continuous integration. I can generate the doc with `make doc` in local so I suppose it's ok.

### CODE REVIEW

**Comment by Drup** [comment]
Not sure why jenkins crashes. We might as well merge and see if things work out ...

**Comment by dannywillems** [comment]
In the same time, I think it could be interesting to add a rule `doc-clean` to remove `doc/client` and `doc/server` which are generated by `make doc`. @vasilisp What do you think? It could be added as dependency to `clean` or `disclean` and to `doc`.

**Comment by dannywillems** [comment]
@Drup First, wikidoc wasn't installed. After that, there were some errors in documentation and a `eliomi` file (`Os_types.eliomi`) wasn't present.

**Comment by dannywillems** [comment]
@Drup I prefered to add `os_types.eliomi` (even if it's the same than `os_types.eliom`) instead of add `os_types.eliom` in `Makefile.options`.

**Comment by dannywillems** [comment]
@Drup Do you know why I have these warnings?
```
...
Warning: Module type PGOCaml_generic.PGOCAML_GENERIC not found
Warning: Module type PGOCaml_generic.PGOCAML_GENERIC not found
Warning: Element Style.Picture not found
Warning: Element add_notification_id not found
Warning: Element Os_handlers.set_personal_data_handler' not found
Warning: Element Os_db.action_link_table not found
Warning: Element Os_handlers.set_password_handler' not found
Warning: Element on_close_session not found
Warning: Element Permission denied not found
Warning: Element Eliom_session.Opt.connected_fun not found
Warning: Element Style.Picture not found
Warning: Element add_notification_id not found
```
(It's the same on Jenkins).

**Comment by Drup** [comment]
Seems like regular ocamldoc babbling. When you use `{!Foo}` and it can't find it, it emits warning. You can ignore them for now.

**Comment by vasilisp** [comment]
The Jenkins "walk failure" error happens from time to time, and for PRs only. I think it will go away if we rebuild the docker bot.

Merging to see what will happen in `master`.

**Comment by vasilisp** [comment]
`master` is clean now, champagne time! Thanks @dannywillems :).

**Comment by dannywillems** [comment]
@vasilisp 🎉  🎉  🎉 Still the PR now.

**Pull request merged**
