### PR TITLE
Update API

### LINKED ISSUE #229: Check API of ocsigen-start (see #236)
See #236

### PR DESCRIPTION
**Pull request by dannywillems**
Fix #229

I pointed out that I forgot lots of things in the API in PR when I documented.
To-do:
- [x] `Os_user_proxy`
- [x] ~~`Os_tools`~~ (see my comment below)
- [x] `Os_services`: module description.
- [x] `Os_request_cache`.
- [x] ~~`Os_notif`~~ (see my comment below)
- [x] `Os_comet`: remove some useless functions I exported when I did the eliomi.

To compile the documentation (I know some people have some difficulties), you need to switch to `4.02.3`, pin `wikidoc` and install `ocsigen-start`. After that, use `make doc`.
Here a copy-past (I suppose you are in the repo ocsigen-start and in the branch of the PR):

```
opam switch wikidoc --alias-of 4.02.3
eval `opam config env`
opam pin add --no-action -y wikidoc https://github.com/ocsigen/wikidoc.git
opam pin add --no-action -y ocsigenserver https://github.com/ocsigen/ocsigenserver.git
opam pin add --no-action -y js_of_ocaml https://github.com/ocsigen/js_of_ocaml.git
opam pin add --no-action -y deriving https://github.com/ocsigen/deriving.git
opam pin add --no-action -y reactiveData https://github.com/ocsigen/reactiveData.git
opam pin add --no-action -y eliom https://github.com/ocsigen/eliom.git
opam pin add --no-action -y ocsigen-toolkit https://github.com/ocsigen/ocsigen-toolkit.git
opam pin add --no-action -y ojquery https://github.com/ocsigen/ojquery.git
opam pin add --no-action -y ocsigen-start https://github.com/ocsigen/ocsigen-start.git
opam install wikidoc ocsigen-start -y
make doc
```

### CODE REVIEW

**Comment by vasilisp** [comment]
Just for future reference, `ojquery` is no longer a dependency of anything. Also, you should be fine with released versions of `deriving` and `js_of_ocaml` (modulo bugs).

**Comment by dannywillems** [comment]
@vasilisp Ok, I will test it and update the README if it's the case.

**Comment by dannywillems** [comment]
- I think `Os_tools` will be removed because it must be in `ocsigen-toolkit` or `Eliom_tools`.
- `Os_notif` must be rewritten by using only `Eliom_notif` (see #80, must be rebased and see what's the difference between `Eliom_notif` and #197 @jrochel @canonici).

For these reasons, I won't document these two files because I think it would be useless.

So, after a review of my english, it can be merged.

**Comment by dannywillems** [comment]
If someone reviews this PR, pay attention to functions I removed from the interface in `Os_comet` and `Os_user_proxy`.

All modifications about API is in the commit `Update API`.

**Comment by balat** [comment]
This PR has lots of conflicts, but I suppose it is still valid?

**Comment by dannywillems** [comment]
@balat I suppose. I can resolve conflicts tonight.

**Comment by dannywillems** [comment]
@balat I fixed all conflicts but review it to be sure I don't remove anything: there were lots of conflicts with huge parts of code.

**Pull request merged**
